// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeH8-gcWAuJx8HWjsNaBgIg8bPxWfeCHM',
    appId: '1:435146315201:web:e6bf02e79b7232def5cb40',
    messagingSenderId: '435146315201',
    projectId: 'porichoy-4b0aa',
    authDomain: 'porichoy-4b0aa.firebaseapp.com',
    storageBucket: 'porichoy-4b0aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXwDF4myhnveY_oiid84LTXU4jISGvoN8',
    appId: '1:435146315201:android:072e39bc7808f157f5cb40',
    messagingSenderId: '435146315201',
    projectId: 'porichoy-4b0aa',
    storageBucket: 'porichoy-4b0aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ewecm-WgZ84_XIBTvCqKSOXywsp2lR4',
    appId: '1:435146315201:ios:6722b824f896d90ef5cb40',
    messagingSenderId: '435146315201',
    projectId: 'porichoy-4b0aa',
    storageBucket: 'porichoy-4b0aa.firebasestorage.app',
    iosBundleId: 'com.example.porichoy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ewecm-WgZ84_XIBTvCqKSOXywsp2lR4',
    appId: '1:435146315201:ios:6722b824f896d90ef5cb40',
    messagingSenderId: '435146315201',
    projectId: 'porichoy-4b0aa',
    storageBucket: 'porichoy-4b0aa.firebasestorage.app',
    iosBundleId: 'com.example.porichoy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeH8-gcWAuJx8HWjsNaBgIg8bPxWfeCHM',
    appId: '1:435146315201:web:d50ddf2cfa89104ef5cb40',
    messagingSenderId: '435146315201',
    projectId: 'porichoy-4b0aa',
    authDomain: 'porichoy-4b0aa.firebaseapp.com',
    storageBucket: 'porichoy-4b0aa.firebasestorage.app',
  );
}
